services:
  backend:
    build: .
    ports:
      - "5000:80"
    networks:
      - sigmaChat
  postgres:
    image: postgres:18
    volumes:
      - sql_data:/var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=JHVHjhvh!
      - POSTGRES_USER=sa
      - POSTGRES_DB=SigmaChatDb
    networks:
      - sigmaChat
  minio:
    image: firstfinger/minio:latest-amd64 
    ports:
      - "9000:9000"
      - "9001:9001"
      - "9002:9002"
    networks:
      - sigmaChat
    volumes:
      - "minio_data:/data"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=jhvhJHVH!
      - MINIO_DEFAULT_BUCKETS=jehovahs-pictures
    user: "0"
volumes:
  sql_data:
  minio_data:
    driver: local

networks:
  sigmaChat:
    name: sigmaChat
